CREATE TABLE `table` (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    category VARCHAR(100),
    broadcast_time VARCHAR(100),
    views VARCHAR(50),
    sales VARCHAR(50),
    revenue VARCHAR(50),
    product_count VARCHAR(50),
    type VARCHAR(20)
);

CREATE TABLE `member` (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    category VARCHAR(100),
    broadcast_time VARCHAR(100),
    views VARCHAR(50),
    sales VARCHAR(50),
    revenue VARCHAR(50),
    product_count VARCHAR(50),
    type VARCHAR(20)
);